# Generated by Django 2.2.3 on 2019-07-07 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0003_pedido_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
